//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.13 at 02:32:50 PM BRT 
//


package br.com.sose.nfe.producao.xsdclasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Dest;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.COFINS;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.COFINS.COFINSNT;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.COFINSST;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.ICMS;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.II;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.IPI;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.IPI.IPINT;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.ISSQN;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.PIS;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.PIS.PISNT;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Det.Imposto.PISST;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Total.ICMSTot;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Emit;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Ide;
import br.com.sose.nfe.producao.xsdclasses.TNFe.InfNFe.Total;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.sose.nfe.producao.xsdclasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

//    private final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");
    private final static QName _NfeProc_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "NfeProc");

    
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.sose.nfe.producao.xsdclasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KeyInfoType }
     * 
     */
    public KeyInfoType createKeyInfoType() {
        return new KeyInfoType();
    }
    
    public TEnviNFe createTEnviNFe() {
        return new TEnviNFe();
    }
    
    public TNFe createTNFe() {
        return new TNFe();
    }
    
    public Ide createIde() {
        return new Ide();
    }
    
    public Imposto createImposto() {
        return new Imposto();
    }
    
    public ICMS createIcms() {
        return new ICMS();
    }
    
    public ICMSSN900 createICMSSN900() {
        return new ICMSSN900();
    }
    
    public IPI createIPI() {
        return new IPI();
    }
    
    public IPINT createIPINT() {
        return new IPINT();
    }
    
    public II createII() {
        return new II();
    }
    
    public ISSQN createIssqn() {
        return new ISSQN();
    }
    
    public PIS createPis() {
        return new PIS();
    }
    
    public PISNT createPisnt() {
        return new PISNT();
    }
    
    public PISST createPisst() {
        return new PISST();
    }
    
    public COFINS createCofins() {
        return new COFINS();
    }
    
    public COFINSST createCofinsst() {
        return new COFINSST();
    }
    
    public COFINSNT createCofinsnt() {
        return new COFINSNT();
    }
    
    public Total createTotal() {
        return new Total();
    }
    
    public ICMSTot createICMSTot() {
        return new ICMSTot();
    }

    public Emit createEmit() {
        return new Emit();
    }
    
    public Dest createDest() {
        return new Dest();
    }
    
    public TEnderEmi createTEnderEmi() {
        return new TEnderEmi();
    }
     
    public TNFe.InfNFe.Det.Prod createProd() {
        return new TNFe.InfNFe.Det.Prod();
    }
    
    public TEnviNFe createEnviNFe() {
        return new TEnviNFe();
    }
    
    public TNFe.InfNFe.Det createDet() {
        return new TNFe.InfNFe.Det();
    }
    
    public TNFe.InfNFe createInfNFe() {
        return new TNFe.InfNFe();
    }
    
    public TNfeProc createNfeProc() {
        return new TNfeProc();
    }
    
    public TRetConsStatServ createRetConsStatServ() {
        return new TRetConsStatServ();
    }
    
    public TCancNFe createCancNFe() {
        return new TCancNFe();
    }
    
    public TConsCad createConsCad() {
        return new TConsCad();
    }
    
    public TConsReciNFe createConsReciNFe() {
        return new TConsReciNFe();
    }
    
    public TConsSitNFe createConsSitNFe() {
        return new TConsSitNFe();
    }
    
    public TConsStatServ createConsStatServ() {
        return new TConsStatServ();
    }
    
    public TEndereco createEndereco() {
        return new TEndereco();
    }
    
    public TEnderEmi createEnderEmi() {
        return new TEnderEmi();
    }
    
    public TInutNFe createInutNFe() {
        return new TInutNFe();
    }
    
    public TLocal createLocal() {
        return new TLocal();
    }
    
    public TProcCancNFe createProcCancNFe() {
        return new TProcCancNFe();
    }
    
    public TProcInutNFe createProcInutNFe() {
        return new TProcInutNFe();
    }
    
    public TProtNFe createProtNFe() {
        return new TProtNFe();
    }
    
    public TRetCancNFe createRetCancNFe() {
        return new TRetCancNFe();
    }
    
    public TRetConsCad createRetConsCad() {
        return new TRetConsCad();
    }
    
    public TRetConsReciNFe createRetConsReciNFe() {
        return new TRetConsReciNFe();
    }
    
    public TRetEnviNFe createRetEnviNFe() {
        return new TRetEnviNFe();
    }
    
    public TRetInutNFe createRetInutNFe() {
        return new TRetInutNFe();
    }
    
    public TVeiculo createVeiculo() {
        return new TVeiculo();
    }


    /**
     * Create an instance of {@link ReferenceType.DigestMethod }
     * 
     */
    public ReferenceType.DigestMethod createReferenceTypeDigestMethod() {
        return new ReferenceType.DigestMethod();
    }

    /**
     * Create an instance of {@link SignatureValueType }
     * 
     */
    public SignatureValueType createSignatureValueType() {
        return new SignatureValueType();
    }

    /**
     * Create an instance of {@link TransformType }
     * 
     */
    public TransformType createTransformType() {
        return new TransformType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link SignedInfoType }
     * 
     */
    public SignedInfoType createSignedInfoType() {
        return new SignedInfoType();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link TransformsType }
     * 
     */
    public TransformsType createTransformsType() {
        return new TransformsType();
    }

    /**
     * Create an instance of {@link X509DataType }
     * 
     */
    public X509DataType createX509DataType() {
        return new X509DataType();
    }

    /**
     * Create an instance of {@link SignedInfoType.SignatureMethod }
     * 
     */
    public SignedInfoType.SignatureMethod createSignedInfoTypeSignatureMethod() {
        return new SignedInfoType.SignatureMethod();
    }

    /**
     * Create an instance of {@link SignedInfoType.CanonicalizationMethod }
     * 
     */
    public SignedInfoType.CanonicalizationMethod createSignedInfoTypeCanonicalizationMethod() {
        return new SignedInfoType.CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     * 
     */
//    @XmlElementDecl(namespace = "testeObj", name = "Signature")
//    public JAXBElement<SignatureType> createSignature(SignatureType value) {
//        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
//    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "NFe")
    public JAXBElement<TNFe> createNfe(TNFe value) {
        return new JAXBElement<TNFe>(_NfeProc_QNAME,TNFe.class, null,  value);
    }

}
